// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	response "github.com/yusank/goim/api/transport/response"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserRelationServiceClient is the client API for UserRelationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRelationServiceClient interface {
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
	GetUserRelation(ctx context.Context, in *GetUserRelationRequest, opts ...grpc.CallOption) (*GetUserRelationResponse, error)
	QueryUserRelationList(ctx context.Context, in *QueryUserRelationListRequest, opts ...grpc.CallOption) (*QueryUserRelationListResponse, error)
	UpdateUserRelation(ctx context.Context, in *UpdateUserRelationRequest, opts ...grpc.CallOption) (*response.BaseResponse, error)
}

type userRelationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRelationServiceClient(cc grpc.ClientConnInterface) UserRelationServiceClient {
	return &userRelationServiceClient{cc}
}

func (c *userRelationServiceClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	out := new(AddFriendResponse)
	err := c.cc.Invoke(ctx, "/api.user.v1.UserRelationService/AddFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRelationServiceClient) GetUserRelation(ctx context.Context, in *GetUserRelationRequest, opts ...grpc.CallOption) (*GetUserRelationResponse, error) {
	out := new(GetUserRelationResponse)
	err := c.cc.Invoke(ctx, "/api.user.v1.UserRelationService/GetUserRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRelationServiceClient) QueryUserRelationList(ctx context.Context, in *QueryUserRelationListRequest, opts ...grpc.CallOption) (*QueryUserRelationListResponse, error) {
	out := new(QueryUserRelationListResponse)
	err := c.cc.Invoke(ctx, "/api.user.v1.UserRelationService/QueryUserRelationList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRelationServiceClient) UpdateUserRelation(ctx context.Context, in *UpdateUserRelationRequest, opts ...grpc.CallOption) (*response.BaseResponse, error) {
	out := new(response.BaseResponse)
	err := c.cc.Invoke(ctx, "/api.user.v1.UserRelationService/UpdateUserRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRelationServiceServer is the server API for UserRelationService service.
// All implementations must embed UnimplementedUserRelationServiceServer
// for forward compatibility
type UserRelationServiceServer interface {
	AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error)
	GetUserRelation(context.Context, *GetUserRelationRequest) (*GetUserRelationResponse, error)
	QueryUserRelationList(context.Context, *QueryUserRelationListRequest) (*QueryUserRelationListResponse, error)
	UpdateUserRelation(context.Context, *UpdateUserRelationRequest) (*response.BaseResponse, error)
	mustEmbedUnimplementedUserRelationServiceServer()
}

// UnimplementedUserRelationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserRelationServiceServer struct {
}

func (UnimplementedUserRelationServiceServer) AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFriend not implemented")
}
func (UnimplementedUserRelationServiceServer) GetUserRelation(context.Context, *GetUserRelationRequest) (*GetUserRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRelation not implemented")
}
func (UnimplementedUserRelationServiceServer) QueryUserRelationList(context.Context, *QueryUserRelationListRequest) (*QueryUserRelationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserRelationList not implemented")
}
func (UnimplementedUserRelationServiceServer) UpdateUserRelation(context.Context, *UpdateUserRelationRequest) (*response.BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRelation not implemented")
}
func (UnimplementedUserRelationServiceServer) mustEmbedUnimplementedUserRelationServiceServer() {}

// UnsafeUserRelationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRelationServiceServer will
// result in compilation errors.
type UnsafeUserRelationServiceServer interface {
	mustEmbedUnimplementedUserRelationServiceServer()
}

func RegisterUserRelationServiceServer(s grpc.ServiceRegistrar, srv UserRelationServiceServer) {
	s.RegisterService(&UserRelationService_ServiceDesc, srv)
}

func _UserRelationService_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRelationServiceServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.user.v1.UserRelationService/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRelationServiceServer).AddFriend(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRelationService_GetUserRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRelationServiceServer).GetUserRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.user.v1.UserRelationService/GetUserRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRelationServiceServer).GetUserRelation(ctx, req.(*GetUserRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRelationService_QueryUserRelationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserRelationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRelationServiceServer).QueryUserRelationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.user.v1.UserRelationService/QueryUserRelationList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRelationServiceServer).QueryUserRelationList(ctx, req.(*QueryUserRelationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRelationService_UpdateUserRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRelationServiceServer).UpdateUserRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.user.v1.UserRelationService/UpdateUserRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRelationServiceServer).UpdateUserRelation(ctx, req.(*UpdateUserRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRelationService_ServiceDesc is the grpc.ServiceDesc for UserRelationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRelationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.v1.UserRelationService",
	HandlerType: (*UserRelationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFriend",
			Handler:    _UserRelationService_AddFriend_Handler,
		},
		{
			MethodName: "GetUserRelation",
			Handler:    _UserRelationService_GetUserRelation_Handler,
		},
		{
			MethodName: "QueryUserRelationList",
			Handler:    _UserRelationService_QueryUserRelationList_Handler,
		},
		{
			MethodName: "UpdateUserRelation",
			Handler:    _UserRelationService_UpdateUserRelation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/relation/v1/user_relation.proto",
}
