name: goim.push.service
version: v0.0.0
http:
  scheme: http
  port: 8081
grpc:
  scheme: grpc
  port: 8083
log:
  level:
  - INFO
  - DEBUG
metadata:
  httpSrv: yes
  grpcSrv: yes
redis:
  addr: 127.0.0.1:6379