// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/transport/response/response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK Code = 0
	// common error codes
	Code_UnknownError  Code = 10001
	Code_InvalidParams Code = 10002
	// user error codes
	Code_UserNotExist              Code = 20001
	Code_UserExist                 Code = 20002
	Code_InvalidUsernameOrPassword Code = 20003
	// relation error codes
	Code_RelationNotExist            Code = 30001
	Code_RelationExist               Code = 30002
	Code_InvalidUpdateRelationAction Code = 30003
	// friend request error codes
	Code_FriendRequestNotExist    Code = 31001
	Code_FriendRequestStatusError Code = 31002
	// push server error codes
	Code_UserNotOnline Code = 40001
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:     "OK",
		10001: "UnknownError",
		10002: "InvalidParams",
		20001: "UserNotExist",
		20002: "UserExist",
		20003: "InvalidUsernameOrPassword",
		30001: "RelationNotExist",
		30002: "RelationExist",
		30003: "InvalidUpdateRelationAction",
		31001: "FriendRequestNotExist",
		31002: "FriendRequestStatusError",
		40001: "UserNotOnline",
	}
	Code_value = map[string]int32{
		"OK":                          0,
		"UnknownError":                10001,
		"InvalidParams":               10002,
		"UserNotExist":                20001,
		"UserExist":                   20002,
		"InvalidUsernameOrPassword":   20003,
		"RelationNotExist":            30001,
		"RelationExist":               30002,
		"InvalidUpdateRelationAction": 30003,
		"FriendRequestNotExist":       31001,
		"FriendRequestStatusError":    31002,
		"UserNotOnline":               40001,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_api_transport_response_response_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_api_transport_response_response_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_api_transport_response_response_proto_rawDescGZIP(), []int{0}
}

// BaseResponse use as define response code and message
type BaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=api.transport.response.Code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_transport_response_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transport_response_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_api_transport_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_transport_response_response_proto protoreflect.FileDescriptor

var file_api_transport_response_response_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x52, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x2a, 0x9d, 0x02, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x91, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x10, 0x92, 0x4e, 0x12, 0x12, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0xa1, 0x9c, 0x01, 0x12,
	0x0f, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0xa2, 0x9c, 0x01,
	0x12, 0x1f, 0x0a, 0x19, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x4f, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0xa3, 0x9c,
	0x01, 0x12, 0x16, 0x0a, 0x10, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0xb1, 0xea, 0x01, 0x12, 0x13, 0x0a, 0x0d, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0xb2, 0xea, 0x01, 0x12, 0x21,
	0x0a, 0x1b, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0xb3, 0xea,
	0x01, 0x12, 0x1b, 0x0a, 0x15, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x99, 0xf2, 0x01, 0x12, 0x1e,
	0x0a, 0x18, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x9a, 0xf2, 0x01, 0x12, 0x13,
	0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10,
	0xc1, 0xb8, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x79, 0x75, 0x73, 0x61, 0x6e, 0x6b, 0x2f, 0x67, 0x6f, 0x69, 0x6d, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_transport_response_response_proto_rawDescOnce sync.Once
	file_api_transport_response_response_proto_rawDescData = file_api_transport_response_response_proto_rawDesc
)

func file_api_transport_response_response_proto_rawDescGZIP() []byte {
	file_api_transport_response_response_proto_rawDescOnce.Do(func() {
		file_api_transport_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_transport_response_response_proto_rawDescData)
	})
	return file_api_transport_response_response_proto_rawDescData
}

var file_api_transport_response_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_transport_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_transport_response_response_proto_goTypes = []interface{}{
	(Code)(0),            // 0: api.transport.response.Code
	(*BaseResponse)(nil), // 1: api.transport.response.BaseResponse
}
var file_api_transport_response_response_proto_depIdxs = []int32{
	0, // 0: api.transport.response.BaseResponse.code:type_name -> api.transport.response.Code
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_transport_response_response_proto_init() }
func file_api_transport_response_response_proto_init() {
	if File_api_transport_response_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_transport_response_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_transport_response_response_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_transport_response_response_proto_goTypes,
		DependencyIndexes: file_api_transport_response_response_proto_depIdxs,
		EnumInfos:         file_api_transport_response_response_proto_enumTypes,
		MessageInfos:      file_api_transport_response_response_proto_msgTypes,
	}.Build()
	File_api_transport_response_response_proto = out.File
	file_api_transport_response_response_proto_rawDesc = nil
	file_api_transport_response_response_proto_goTypes = nil
	file_api_transport_response_response_proto_depIdxs = nil
}
