name: goim.msg.service
version: v0.0.0
http:
  scheme: grpc
  port: 8063
log:
  level:
  - INFO
  - DEBUG
metadata:
  grpcSrv: yes
redis:
  addr: 127.0.0.1:6379
mq:
  addr:
    - 127.0.0.1:9978
  maxRetry: 3