name: goim.gateway.service
version: v0.0.0
http:
  scheme: http
  port: 18071
grpc:
  scheme: grpc
  port: 18073
log:
  level:
  - INFO
  - DEBUG
metadata:
  httpSrv: yes
mq:
  addr:
    - http://127.0.0.1:9876