name: golangci-lint
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v2
              with:
                  version: latest
            - name: Vet
              run: go vet -v ./...